### ISSUE TITLE
tables by lines?

### ISSUE THREAD

**Issue by j2l** [gristlabs/grist-api#7]
Hi,
I can get a table by column `/tables/Contact/data` but how can I get it (or transform it) as an array of objects by lines?
```
[ 
{"id": 1, 'Website": "www.devhub.com", "First_Name": "Ibrahim", ...}, 
{...}
]
```
Like most CSV to JSON do.

In addition to a solution, is there a reason to send it by column? Is it search related?

**Comment by paulfitz** [comment]
Hi @j2l, the `grist-api` library can do that for you, if you are using javascript/node. See the `fetchTable` method. But it sounds like you may be using the API directly? If you let me know the particular language or framework you're using, I may be able to suggest how to transform the data in it.

Grist internally has a representation optimized for columnar operations, which is why the API is as it is. You're not the first to find it surprising though, so we're considering adding a row-based API.

**Comment by j2l** [comment]
Thank you @paulfitz 
Yes, I'm thinking of a true serverless setup using MIT AppInventor (very basic bricks). Many users are looking for a simple REST API delivering easy to drill JSON. A row-based API route would help.
I'm also interested with a NodeJS setup, I can imagine how a for loop through each index could work but if you already have something would you please share it?

**Comment by j2l** [comment]
I tried fetchTable but always get a 401 status code.
ReadMe states `const DOC_URL = "https://subdomain.getgrist.com/doc/12345678-2761-4ef2-bc28-310e634754fb";` but doc/ is not valid, even with docs/ I get a 401, while it works with Postman.
Do I need CORS to call it from server using grist-api?

**Comment by paulfitz** [comment]
An endpoint like https://public.getgrist.com/api/docs/911KcgKA95oQ gives metadata about a doc (e.g. its name), rather than data in the doc (e.g. tables and rows). https://public.getgrist.com/doc/911KcgKA95oQ is an older way to write a link to a document (if you visit it, you'll see it now redirects to something like https://public.getgrist.com/911KcgKA95oQ/Minimal-Custom-Widget). All grist-api does with the `DOC_URL` is to extract a document id from it, and then use it to make API calls.

If I run this (with `GRIST_API_KEY` defined):
```js
const {GristDocAPI} = require('grist-api');
// Put here the URL of your document.
const DOC_URL = "https://public.getgrist.com/911KcgKA95oQ/Minimal-Custom-Widget";
async function main() {
  const api = new GristDocAPI(DOC_URL);
  // Fetch all rows.
  const data = await api.fetchTable('Animal_Names');
  console.log(data);
}
main();
```
I see this:
```js
[ { id: 1,
    manualSort: 1,
    Rating: 3,
    Name: 'Fuzzybuns',
    Animal: 'Rabbit' },
  { id: 2, manualSort: 2, Rating: 2, Name: 'Howler', Animal: 'Dog' },
  { id: 3,
    manualSort: 3,
    Rating: 8,
    Name: 'Whiskey',
    Animal: 'Mouse' },
  { id: 4, manualSort: 4, Rating: 4, Name: 'Paddy', Animal: 'Cat' },
  { id: 5,
    manualSort: 5,
    Rating: 1,
    Name: 'Twinkletoes',
    Animal: 'Cat' } ]
```
Does that work for you?

**Comment by j2l** [comment]
Hi @paulfitz thank you again.
> const DOC_URL = "https://public.getgrist.com/911KcgKA95oQ/Minimal-Custom-Widget";

doesn't work for me, it doesn't redirect but throws a HTML page.
Only links with `/api/` are sending JSON for me.

**Comment by j2l** [comment]
And here's the Node-Red version, using the grist-API and functionx (constant npm libraries, installable via the palette):
```
var temp = msg.payload
msg.payload = {}
let { GristDocAPI } = require("grist-api@latest");
let DOC_URL = "https://public.getgrist.com/doc/911KcgKA95oQ";
let api = new GristDocAPI(DOC_URL);
let data = await api.fetchTable('Animal_Names');
msg.payload.data = data;
return msg;
```
Node-Red is considered as running within a global async function BUT if `msg.payload` has content, the `return msg` takes the shortcut before waiting for fetchTable, so you need to shift data elsewhere (temp) and reset `msg.payload` before all the rest :smile:
